### PR TITLE
Update pym to 1.1.2

### PR DESCRIPTION
**Pull request by benlk**
## Changes
- updates Pym.js to version 1.1.1, minified, for #12
- adds instructions to plugin docs for updating Pym.js
- adds notes about licenses
- bumps plugin version number to 1.1.1, to match the Pym version, with the goal of keeping the plugin version and the `x.y.z` version numbers equal to they Pym version numbers, with plugin bugfixes being designated by a fourth digit `x.y.z.1`.

### CODE REVIEW

**Comment by jjelosua** [comment]
@benlk Taking a look at the code found one small typo (not due to this change): https://github.com/INN/pym-shortcode/blob/e9470092195ab6ff23da06eb92a70d85ddd8b527/pym-shortcode.php#L42

I am curious if it would not be better or simpler to use the [autoinit](http://blog.apps.npr.org/pym.js/) version of pym instead of instantiating the parent on an inline script....but maybe there are loading issues that I am unaware of.

screenshot 2016-10-06 23 01 44

**Comment by jjelosua** [comment]
On the README a couple of things too:
- it indicates that the pym source is `js/pym.src` instead of `js/pym.js` and the example for pymoptions should be `[pym src="child.html" pymoptions=" xdomain: '\\*\.npr\.org' "]` instead of `[pym src="child.html" pymoptions=" xdomain: '*\.npr\.org' "]`

**Comment by benlk** [comment]
A very belated thanks for the review! Autoinit might work better, but because of legacy support for stuff like old versions of Hearken's pym, I think we're going to stick with the current initialization for now.

- [x] update to 1.1.2: https://github.com/nprapps/pym.js/releases
- [x] bump version number to 1.1.2
- [x] clean up typos

**Comment by benlk** [comment]
I think that's everything. This PR now bumps the version number and Pym to 1.1.2, puts Pym 1.1.2 at a filename that matches NPR's naming scheme, and updates a whole lot of documentation references.

**Review by rclachance — APPROVED** [review]

**Pull request merged**
