### PR TITLE
Rename the plugin to "Pym.js Embeds" in most places.

### PR DESCRIPTION
**Pull request by benlk**
This name is chosen becuse it lacks the clunkiness of "shortcode and block".

In an email from Alyson Hurt, NPR Visuals Team member:

> I'm afraid I don't know enough about WordPress and user/developer community expectations to be able to weigh in with an informed opinion on the naming question. All that said, your suggestion of "Pym.js embeds" gets around the shortcode vs. block question entirely and might be a reasonable way to go.

And that's good enough for me.

Resolves https://github.com/INN/pym-shortcode/issues/39

### CODE REVIEW

**Comment by kaylima** [comment]
@benlk is there a reason you're choosing "Pym.js embeds" instead of "Pym embeds" (sans the .js)?

**Comment by benlk** [comment]
I don't have a considered reason for choosing "Pym.js Embeds" over "Pym Embeds". Do you think "Pym Embeds" would be better?

**Comment by benlk** [comment]
Further thoughts:

Pym Embeds:

- follows existing "Pym Shortcode" naming scheme
- less awkward to say, saves two syllables
- less-drastic rename
- style guidelines for this plugin's docs are simpler, because we won't have conflicting presentations of "Pym.js" in "Pym.js Embeds" referring to the plugin vs "`Pym.js`" referring to the library.

Pym.js Embeds

- Highlights that this is a JavaScript thing, setting the expectation that it's somewhat technical
- Uses same branding as NPR's library, for better SEO

@alykat Does NPR have guidelines for Pym.js branding? The docs at http://blog.apps.npr.org/pym.js/ seem to use "Pym" and "`Pym.js`" and "`pym.js`" fairly interchangeably, notably calling users of the library "Pym users" in the 1.3.2 release note.

**Comment by alykat** [comment]
No formal guidelines on our end. We tend to use "Pym" as internal shorthand, but "pym.js" (capitalized or lowercase) is more precise, especially when addressing a broader audience that may not already know what it is.

**Comment by benlk** [comment]
Search results for "pym wordpress" and "pym.js wordpress" both have this plugin listed in the top 5 on DuckDuckGo and Google, so I'm not too concerned about SEO.

I agree with Aly's point that "Pym.js" is the more-precise name.

**Pull request merged**
